version: '3.8'

services:

  redis:
    image: redis:7
    container_name: redis


  db_app:
    image: db_app
    build:
      context: ./database
    container_name: db_app
    restart: always
    depends_on:
      - redis
    env_file:
      - "database/.env"
    command: sh -c "gunicorn main:app  --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:7777"


  bot:
    image: bot
    container_name: bot
    stop_signal: SIGINT
    build:
      context: ./bot
    working_dir: "/usr/src/bot/bot"
    volumes:
      - .:/usr/src/bot
    command: python3 -m bot
    restart: always
    env_file:
      - "bot/.env"
    depends_on:
      - db_app


  app:
    image: app
    build:
      context: ./app
    container_name: app
    restart: always
    depends_on:
      - db_app
    env_file:
      - "app/.env"
    #      volumes:
    #        - "./certs:/usr/src/certs"
    command: sh -c "gunicorn main:app  --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"


  nginx:
    build:
      context: .
      dockerfile: "./app/Dockerfile.nginx"
    container_name: app_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    links:
      - app


