"""empty message

Revision ID: 04a0469e68e7
Revises: 90463bf36113
Create Date: 2023-10-04 16:22:04.596417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a0469e68e7'
down_revision: Union[str, None] = '90463bf36113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('telegraph_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'telegraph_token')
    # ### end Alembic commands ###
