"""empty message

Revision ID: 07bd53684a9d
Revises: 04a0469e68e7
Create Date: 2023-10-05 11:53:41.349968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bd53684a9d'
down_revision: Union[str, None] = '04a0469e68e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'telegraph_token')
    op.add_column('users', sa.Column('telegraph_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegraph_token')
    op.add_column('files', sa.Column('telegraph_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
