"""empty message

Revision ID: 420d15b89d6b
Revises: 07bd53684a9d
Create Date: 2023-10-16 00:50:48.628258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420d15b89d6b'
down_revision: Union[str, None] = '07bd53684a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calculation_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('telegraph_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegraph_count')
    op.drop_column('users', 'calculation_count')
    # ### end Alembic commands ###
