"""empty message

Revision ID: 70e33b38455f
Revises: 420d15b89d6b
Create Date: 2023-10-19 17:20:47.855081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e33b38455f'
down_revision: Union[str, None] = '420d15b89d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('handler', sa.String(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('buttons', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_texts')
    # ### end Alembic commands ###
